name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to WPX via rsync
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./dist/ # Asegúrate que tu build sea 'dist'
          remote_path: /public_html/
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_port: 2222
        env:
          ssh_private_key: "" # No la usamos porque usaremos password
          remote_password: ${{ secrets.FTP_PASSWORD }}